package pkg

type Datum struct {
	Command     string
	Content     string
	Description string
}

type Data map[string][]Datum

func Commands() Data {
	return Data{
		"ノーマルモード": {
			{Command: "%", Content: "対照となるカッコ間を移動", Description: ""},
			{Command: "ci\"", Content: "\t\"\" で囲われたワードを削除", Description: "iの部分はaでもいい。a: 両端を含む, i: 両端を含まない"},
			{Command: "Shift + ^", Content: "行の先頭文字の頭まで移動", Description: ""},
			{Command: "f", Content: "同じ行から文字を探す(次のもの)", Description: ""},
			{Command: "F", Content: "同じ行から文字を探す(前のもの)", Description: ""},
			{Command: ";", Content: "次の検索結果にいく", Description: ""},
			{Command: ",", Content: "前の検索結果にいく", Description: "カスタムしているので現在は使えない"},
			{Command: "t", Content: "行末に向けて最初に見つかったもの", Description: ""},
			{Command: "T", Content: "行頭に向けて最初に見つかったもの", Description: ""},
			{Command: "{", Content: "次の文節に移動する", Description: "関数ごとなどで移動"},
			{Command: "}", Content: "前の文節に移動する", Description: "関数ごとなどで移動"},
			{Command: "'", Content: "前のマークの場所に移動", Description: ""},
			{Command: "ct=", Content: "=までの範囲を削除する(=を含まない)", Description: ""},
			{Command: "cf=", Content: "=までの範囲を削除する(=を含む)", Description: "const XXX = を return などに変えたい時に使う"},
			{Command: "gi", Content: "最後にinsertモードを終了した場所に戻ってinsertモードに切り替える", Description: ""},
			{Command: "ctrl + f", Content: "次へページ送り", Description: ""},
			{Command: "ctrl + b", Content: "前へページ送り", Description: ""},
			{Command: "zz", Content: "カーソル部が真ん中にいくように調整", Description: ""},
			{Command: "zt", Content: "カーソル部が上にいくように調整", Description: ""},
			{Command: "zb", Content: "カーソル部が下にいくように調整", Description: ""},
			{Command: "m{任意のキー}", Content: "任意のキーにマークをつけることができる", Description: ""},
			{Command: "`{任意のキー}", Content: "マークの位置に飛ぶことができる", Description: ""},
			{Command: "ctrl + o", Content: "直前のジャンプ前の位置に戻る", Description: ""},
			{Command: "ctrl + ]", Content: "呼び出し元にジャンプ/呼び出し先にジャンプ", Description: ""},
		},
		"ブックマーク(マーク)": {
			{Command: "m{a-z}", Content: "ローカルマーク(現在のファイル内)を設定", Description: "小文字のマークはファイル内でのみ有効"},
			{Command: "m{A-Z}", Content: "グローバルマーク(ファイル間)を設定", Description: "大文字のマークはファイルをまたいで有効"},
			{Command: "`{a-zA-Z}", Content: "マークした位置の正確な場所(行と列)に移動", Description: "バッククォートを使用"},
			{Command: "'{a-zA-Z}", Content: "マークした行の先頭に移動", Description: "シングルクォートを使用"},
			{Command: ":marks", Content: "設定されているマークの一覧を表示", Description: ""},
			{Command: ":delmarks {marks}", Content: "指定したマークを削除", Description: "例: :delmarks a b c"},
			{Command: ":delmarks!", Content: "すべてのローカルマーク(a-z)を削除", Description: ""},
			{Command: "``", Content: "最後にジャンプした位置に戻る", Description: "バッククォート2つ"},
			{Command: "''", Content: "最後にジャンプした行の先頭に戻る", Description: "シングルクォート2つ"},
			{Command: "`.", Content: "最後に編集した位置に移動", Description: ""},
			{Command: "`^", Content: "最後にInsertモードを抜けた位置に移動", Description: ""},
			{Command: "`[", Content: "最後にヤンクまたは変更したテキストの開始位置", Description: ""},
			{Command: "`]", Content: "最後にヤンクまたは変更したテキストの終了位置", Description: ""},
		},
		"コマンドモード": {
			{Command: "/{word}", Content: "n で次へ進み、N で 1 つ前に戻る", Description: "検索を行う"},
		},
		"ビジュアルブロックモード": {
			{Command: "ctrl-v -> I -> Esc", Content: "同じ箇所に同じ文字列を追加する", Description: ""},
			{Command: "ctrl-a / ctrl-x", Content: "数字のインクリメント/デクリメント", Description: ""},
			{Command: "g<ctrl-a> / g<ctrl-x>", Content: "数字の「連番で」インクリメント/デクリメント", Description: ""},
			{Command: "o", Content: "反対方向にブロックを伸ばすことができる", Description: ""},
		},
		"ファイル一覧": {
			{Command: "-", Content: "一つ上のディレクトリに移動", Description: ""},
			{Command: "u ←→ U", Content: "一つ前のディレクトリに戻る", Description: ""},
			{Command: "ctrl + w → s", Content: "水平分割", Description: ""},
			{Command: "ctrl + w → v", Content: "垂直分割", Description: ""},
			{Command: "ctrl + w → + h j k l\t", Content: "ブラウザ移動", Description: ""},
			{Command: "ctrl + w → + x or crtl + x\t", Content: "次のウィンドウと入れ替える", Description: ""},
			{Command: "ctrl + w → + r or crtl + r", Content: "ウィンドウ一を下 / 右へ回転させる", Description: ""},
			{Command: "ctrl + w → + R or crtl + R\t", Content: "ウィンドウ一下 / 右へ回転させる", Description: ""},
			{Command: "ctrl + w → K", Content: "ウィンドウを最上段に移動し、幅を最大にする", Description: ""},
			{Command: "ctrl + w → J", Content: "ウィンドウを最下段に移動し、幅を最大にする", Description: ""},
			{Command: "ctrl + w → H", Content: "ウィンドウを最左段に移動し、幅を最大にする", Description: ""},
			{Command: "ctrl + w → L", Content: "ウィンドウを最右段に移動し、幅を最大にする", Description: ""},
			{Command: "ctrl + w → T", Content: "ウィンドウを新しいタブページへ移動する", Description: ""},
		},
		"LSP補完": {
			{Command: "Ctl + y", Content: "選択中の補完を選択して適用", Description: ""},
		},
		"vim-surround": {
			{Command: "d s [e]", Content: "eを削除", Description: "delete surround"},
			{Command: "c s [e] [d]", Content: "eをd に変更", Description: "change surround"},
			{Command: "y s [mo] [d]", Content: "mo(モーション)を使って、dで囲む", Description: "you surround"},
			{Command: "S [d]", Content: "dで囲む（注： ヴィジュアルモードの時のみ）", Description: "Sorround(注: Sは大文字)"},
		},
		"レジスタ": {
			{Command: "\"{register}y", Content: "指定したレジスタにヤンク", Description: "例: \"ayw (レジスタaに単語をヤンク)"},
			{Command: "\"{register}p", Content: "指定したレジスタから貼り付け", Description: "例: \"ap (レジスタaから貼り付け)"},
			{Command: "\"{register}d", Content: "指定したレジスタに削除", Description: "例: \"add (レジスタaに現在行を削除)"},
			{Command: ":reg", Content: "すべてのレジスタの内容を表示", Description: ":registers とも記述可能"},
			{Command: ":reg {register}", Content: "指定したレジスタの内容を表示", Description: "例: :reg a"},
			{Command: "\"0", Content: "最後にヤンクした内容", Description: "デフォルトのヤンクレジスタ"},
			{Command: "\"_", Content: "ブラックホールレジスタ", Description: "削除した内容を保存しない"},
			{Command: "\"+", Content: "システムクリップボード", Description: "Linuxでは +clipboard が必要"},
			{Command: "\"*", Content: "選択領域用クリップボード", Description: "Linuxでは +clipboard が必要"},
			{Command: "\".", Content: "最後に挿入したテキスト", Description: ""},
			{Command: "\":", Content: "最後に実行したコマンド", Description: ""},
			{Command: "\"/", Content: "最後に検索したパターン", Description: ""},
		},
		"検索と置換": {
			{Command: "/{pattern}", Content: "前方に検索", Description: "nで次、Nで前"},
			{Command: "?{pattern}", Content: "後方に検索", Description: "nで次、Nで前"},
			{Command: "*", Content: "カーソル下の単語を前方に検索", Description: "完全一致"},
			{Command: "#", Content: "カーソル下の単語を後方に検索", Description: "完全一致"},
			{Command: "g*", Content: "カーソル下の単語を前方に検索", Description: "部分一致"},
			{Command: "g#", Content: "カーソル下の単語を後方に検索", Description: "部分一致"},
			{Command: ":s/old/new", Content: "現在行の最初のoldをnewに置換", Description: ""},
			{Command: ":s/old/new/g", Content: "現在行のすべてのoldをnewに置換", Description: ""},
			{Command: ":s/old/new/gc", Content: "現在行を確認しながら置換", Description: "cはconfirm"},
			{Command: ":%s/old/new/g", Content: "ファイル全体のoldをnewに置換", Description: ""},
			{Command: ":{range}s/old/new/g", Content: "指定範囲のoldをnewに置換", Description: "例: :10,20s/old/new/g"},
			{Command: ":g/{pattern}/d", Content: "パターンに一致する行を削除", Description: "例: :g/^$/d (空行を削除)"},
			{Command: ":g/{pattern}/s/old/new/g", Content: "パターンに一致する行のみ置換", Description: ""},
			{Command: ":v/{pattern}/d", Content: "パターンに一致しない行を削除", Description: "vはinvert"},
			{Command: "n", Content: "次の検索結果へ", Description: ""},
			{Command: "N", Content: "前の検索結果へ", Description: ""},
		},
		"タブ操作": {
			{Command: ":tabnew", Content: "新しいタブを開く", Description: ":tabnew ファイル名 でファイルを開く"},
			{Command: ":tabe {file}", Content: "新しいタブでファイルを開く", Description: "tabedit の短縮形"},
			{Command: "gt", Content: "次のタブに移動", Description: "go to next tab"},
			{Command: "gT", Content: "前のタブに移動", Description: "go to previous tab"},
			{Command: "{N}gt", Content: "N番目のタブに移動", Description: "例: 3gt で3番目のタブ"},
			{Command: ":tabclose", Content: "現在のタブを閉じる", Description: ":tabc とも記述可能"},
			{Command: ":tabonly", Content: "現在のタブ以外をすべて閉じる", Description: ":tabo とも記述可能"},
			{Command: ":tabfirst", Content: "最初のタブに移動", Description: ":tabfir とも記述可能"},
			{Command: ":tablast", Content: "最後のタブに移動", Description: ":tabl とも記述可能"},
			{Command: ":tabnext", Content: "次のタブに移動", Description: ":tabn または gt"},
			{Command: ":tabprevious", Content: "前のタブに移動", Description: ":tabp または gT"},
			{Command: ":tabmove {N}", Content: "タブをN番目の位置に移動", Description: "例: :tabmove 0 (先頭へ)"},
		},
		"マクロ": {
			{Command: "q{register}", Content: "マクロの録画を開始", Description: "例: qa (レジスタaに録画開始)"},
			{Command: "q", Content: "マクロの録画を終了", Description: "録画中に押すと終了"},
			{Command: "@{register}", Content: "指定したレジスタのマクロを実行", Description: "例: @a (レジスタaのマクロ実行)"},
			{Command: "@@", Content: "最後に実行したマクロを再実行", Description: ""},
			{Command: "{N}@{register}", Content: "マクロをN回実行", Description: "例: 10@a (レジスタaを10回実行)"},
			{Command: ":@{register}", Content: "コマンドラインでマクロを実行", Description: "例: :@a"},
			{Command: ":@:", Content: "最後に実行したコマンドラインを再実行", Description: ""},
			{Command: ":reg {register}", Content: "レジスタに記録されたマクロを確認", Description: "例: :reg a"},
		},
		"行番号とジャンプ": {
			{Command: ":{N}", Content: "N行目にジャンプ", Description: "例: :100 (100行目に移動)"},
			{Command: "gg", Content: "ファイルの先頭行にジャンプ", Description: ""},
			{Command: "G", Content: "ファイルの最後の行にジャンプ", Description: ""},
			{Command: "{N}G", Content: "N行目にジャンプ", Description: "例: 100G (100行目に移動)"},
			{Command: ":set number", Content: "行番号を表示", Description: ":set nu とも記述可能"},
			{Command: ":set nonumber", Content: "行番号を非表示", Description: ":set nonu とも記述可能"},
			{Command: ":set relativenumber", Content: "相対行番号を表示", Description: ":set rnu とも記述可能"},
			{Command: ":set number relativenumber", Content: "絶対行番号と相対行番号の両方を表示", Description: ":set nu rnu"},
			{Command: "Ctrl + g", Content: "現在の行番号とファイル情報を表示", Description: ""},
			{Command: "''", Content: "最後にジャンプした行の先頭に戻る", Description: "シングルクォート2つ"},
			{Command: "``", Content: "最後にジャンプした正確な位置に戻る", Description: "バッククォート2つ"},
			{Command: "{N}%", Content: "ファイルのN%の位置にジャンプ", Description: "例: 50% (中央に移動)"},
			{Command: "H", Content: "画面上の最初の行に移動", Description: "High"},
			{Command: "M", Content: "画面中央の行に移動", Description: "Middle"},
			{Command: "L", Content: "画面最下行に移動", Description: "Low"},
		},
		"インデント操作": {
			{Command: ">>", Content: "現在行をインデント(右にシフト)", Description: ""},
			{Command: "<<", Content: "現在行をアンインデント(左にシフト)", Description: ""},
			{Command: "{N}>>", Content: "N行をインデント", Description: "例: 3>> (3行をインデント)"},
			{Command: "{N}<<", Content: "N行をアンインデント", Description: "例: 3<< (3行をアンインデント)"},
			{Command: ">}", Content: "現在位置から次の段落の終わりまでインデント", Description: ""},
			{Command: "<}", Content: "現在位置から次の段落の終わりまでアンインデント", Description: ""},
			{Command: ">G", Content: "現在行からファイル末尾までインデント", Description: ""},
			{Command: "={motion}", Content: "選択範囲を自動インデント", Description: "例: == (現在行), =G (現在行から末尾まで)"},
			{Command: "==", Content: "現在行を自動インデント", Description: ""},
			{Command: "gg=G", Content: "ファイル全体を自動インデント", Description: ""},
			{Command: ":set shiftwidth={N}", Content: "インデント幅をNに設定", Description: "例: :set shiftwidth=4"},
			{Command: ":set tabstop={N}", Content: "タブ文字の幅をNに設定", Description: "例: :set tabstop=4"},
			{Command: ":set expandtab", Content: "タブをスペースに展開", Description: ":set et"},
			{Command: ":set noexpandtab", Content: "タブをスペースに展開しない", Description: ":set noet"},
		},
	}
}

func Header() []string {
	return []string{"Command", "Content", "Description"}
}
